version: "3.6"

services:
    document_signing_develop:
        image: document_signing_develop
        container_name: document-signing-develop
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - "7012:7012"
        volumes:
            - /root/logs:/app/logs
            - /root/uploads/:/app/uploads/
networks:
    default:
        external:
            name: localhost
